from __future__ import annotations

NBA_TEAM_FORUM_LABELS = {
    "hawks": "老鹰专区",
    "celtics": "凯尔特人专区",
    "nets": "篮网专区",
    "hornets": "黄蜂专区",
    "bulls": "公牛专区",
    "cavaliers": "骑士专区",
    "mavericks": "独行侠专区",
    "nuggets": "掘金专区",
    "pistons": "活塞专区",
    "warriors": "勇士专区",
    "rockets": "火箭专区",
    "pacers": "步行者专区",
    "clippers": "快船专区",
    "lakers": "湖人专区",
    "grizzlies": "灰熊专区",
    "heat": "热火专区",
    "bucks": "雄鹿专区",
    "timberwolves": "森林狼专区",
    "pelicans": "鹈鹕专区",
    "knicks": "尼克斯专区",
    "thunder": "雷霆专区",
    "magic": "魔术专区",
    "76ers": "76人专区",
    "suns": "太阳专区",
    "blazers": "开拓者专区",
    "kings": "国王专区",
    "spurs": "马刺专区",
    "raptors": "猛龙专区",
    "jazz": "爵士专区",
    "wizards": "奇才专区",
}

_ALIAS_TO_LABEL = {
    "nba": "NBA版",
    "cba": "CBA版",
    "hawks": "老鹰专区",
    "atl": "老鹰专区",
    "atlanta": "老鹰专区",
    "celtics": "凯尔特人专区",
    "bos": "凯尔特人专区",
    "boston": "凯尔特人专区",
    "nets": "篮网专区",
    "bkn": "篮网专区",
    "brooklyn": "篮网专区",
    "hornets": "黄蜂专区",
    "cha": "黄蜂专区",
    "charlotte": "黄蜂专区",
    "bulls": "公牛专区",
    "chi": "公牛专区",
    "chicago": "公牛专区",
    "cavaliers": "骑士专区",
    "cavs": "骑士专区",
    "cle": "骑士专区",
    "cleveland": "骑士专区",
    "mavericks": "独行侠专区",
    "mavs": "独行侠专区",
    "dal": "独行侠专区",
    "dallas": "独行侠专区",
    "nuggets": "掘金专区",
    "den": "掘金专区",
    "denver": "掘金专区",
    "pistons": "活塞专区",
    "det": "活塞专区",
    "detroit": "活塞专区",
    "warriors": "勇士专区",
    "gsw": "勇士专区",
    "golden state": "勇士专区",
    "rockets": "火箭专区",
    "hou": "火箭专区",
    "houston": "火箭专区",
    "pacers": "步行者专区",
    "ind": "步行者专区",
    "indiana": "步行者专区",
    "clippers": "快船专区",
    "clips": "快船专区",
    "lac": "快船专区",
    "lakers": "湖人专区",
    "lal": "湖人专区",
    "grizzlies": "灰熊专区",
    "mem": "灰熊专区",
    "memphis": "灰熊专区",
    "heat": "热火专区",
    "mia": "热火专区",
    "miami": "热火专区",
    "bucks": "雄鹿专区",
    "mil": "雄鹿专区",
    "milwaukee": "雄鹿专区",
    "timberwolves": "森林狼专区",
    "wolves": "森林狼专区",
    "min": "森林狼专区",
    "minnesota": "森林狼专区",
    "pelicans": "鹈鹕专区",
    "pels": "鹈鹕专区",
    "nop": "鹈鹕专区",
    "new orleans": "鹈鹕专区",
    "knicks": "尼克斯专区",
    "nyk": "尼克斯专区",
    "new york": "尼克斯专区",
    "thunder": "雷霆专区",
    "okc": "雷霆专区",
    "magic": "魔术专区",
    "orl": "魔术专区",
    "orlando": "魔术专区",
    "76ers": "76人专区",
    "sixers": "76人专区",
    "phi": "76人专区",
    "philly": "76人专区",
    "philadelphia": "76人专区",
    "suns": "太阳专区",
    "phx": "太阳专区",
    "phoenix": "太阳专区",
    "blazers": "开拓者专区",
    "trail blazers": "开拓者专区",
    "por": "开拓者专区",
    "portland": "开拓者专区",
    "kings": "国王专区",
    "sac": "国王专区",
    "sacramento": "国王专区",
    "spurs": "马刺专区",
    "sas": "马刺专区",
    "san antonio": "马刺专区",
    "raptors": "猛龙专区",
    "tor": "猛龙专区",
    "toronto": "猛龙专区",
    "jazz": "爵士专区",
    "uta": "爵士专区",
    "utah": "爵士专区",
    "wizards": "奇才专区",
    "was": "奇才专区",
    "washington": "奇才专区",
}


def normalize_hupu_forum(forum: str | None) -> str | None:
    """Normalize Hupu forum inputs into user-facing Chinese forum labels."""
    if forum is None:
        return None
    raw = forum.strip()
    if not raw:
        return None
    if raw in {"NBA版", "CBA版"} or raw.endswith("专区"):
        return raw
    return _ALIAS_TO_LABEL.get(raw.lower(), raw)
