"""add two metrics to player

Revision ID: 02ceaf133423
Revises: 
Create Date: 2024-06-23 14:16:42.503758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '02ceaf133423'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='Team')
    op.create_foreign_key(None, 'Team', 'Team', ['canonical_team_id'], ['team_id'])
    op.drop_column('Team', 'season')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('season', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'Team', type_='foreignkey')
    op.create_index('id', 'Team', ['id'], unique=True)
    # ### end Alembic commands ###
