"""add shot made and attempt to player metric

Revision ID: ee300034a781
Revises: 02ceaf133423
Create Date: 2024-06-23 14:56:41.180546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee300034a781'
down_revision: Union[str, None] = '02ceaf133423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PlayerSeasonMetrics', sa.Column('shot_made', sa.Float(), nullable=True))
    op.add_column('PlayerSeasonMetrics', sa.Column('shot_attempt', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PlayerSeasonMetrics', 'shot_attempt')
    op.drop_column('PlayerSeasonMetrics', 'shot_made')
    # ### end Alembic commands ###
